#!/bin/sh

# Setup build directory
#
cd `dirname $0`/..
if [ -d build_source_package ]; then
	rm -rf build_source_package
fi
mkdir build_source_package
cd build_source_package

# Make source package
#
cmake ..
make package_source
version=`grep VERSION config.h | cut -f2 -d'"'`
mv hiawatha-${version}.tar.gz ..

# Done
#
cd ..
rm -rf build_source_package
