#!/bin/sh

echo "Removing current PolarSSL library."
rm -rf include
rm -rf library

echo "Downloading latest PolarSSL library."
wget -qO polarssl-latest.tgz https://polarssl.org/download/latest-stable
if [ ! -s polarssl-latest.tgz ]; then 
	echo "Download error."
	exit
fi

echo "Installing PolarSSL."
tar -xzf polarssl-latest.tgz
dir=`tar -tzf polarssl-latest.tgz | head -n1`
mv ${dir}ChangeLog .
mv ${dir}include .
mv ${dir}library .

echo "Cleaning up."
rm -rf ${dir}
rm polarssl-latest.tgz
